name: ffmpeg_filter_app
description: A Flutter Windows app to filter MKV files by removing English audio and undesired subtitles.
publish_to: 'none'
version: 1.0.0+1

# Dart SDK version. Adjust to match your local Flutter setup.
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.3
  shared_preferences: ^2.2.2
  desktop_drop: ^0.4.4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true